baseURL = "https://kubevisor.io/"
languageCode = "en-us"
title = "Kubevisor"

[params]
author = "Link Society"
zapier = "https://hooks.zapier.com/hooks/catch/7255418/ow4b2ez/silent/"

[markup.goldmark.renderer]
unsafe=true
