baseURL = "https://kubevisor.io/"
languageCode = "en-us"
title = "Kubevisor"

[params]
logo = "/gfx/Logo_Kubevisor.png"
author = "Link-Society"
description = "Dockerized supervision on Kubernetes"
zapier = "https://hooks.zapier.com/hooks/catch/7255418/ow4b2ez/silent/"

[markup.goldmark.renderer]
unsafe=true
